### PR TITLE
fix: temporary hold nunjucks version to ~3.0.1

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

nunjucks 3.1.0 break, `cache` is gone.
- https://travis-ci.org/eggjs/egg-view-nunjucks/jobs/344959780
- https://github.com/mozilla/nunjucks/compare/v3.0.1...v3.1.0

### CODE REVIEW

**Comment by popomore** [comment]
node security 还是 nunjucks 的依赖

**Comment by popomore** [comment]
发布吧

**Comment by atian25** [comment]
2.1.5

**Comment by atian25** [comment]
https://github.com/mozilla/nunjucks/issues/1074

**Pull request merged**
