### PR TITLE
chore: code style

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
@popomore 看看这个, 另外, 有空整个库 review 一次, ok 后就发 1.x 了

**Comment by popomore** [comment]
其他 +1

**Comment by atian25** [comment]
其他?

**Comment by atian25** [comment]
0.7.0

**Pull request merged**
