### PR TITLE
test: change chai.js to power-assert

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

更清晰, 更简单的 assert
image

同步自 https://github.com/eggjs/egg-boilerplate-simple/blob/master/boilerplate/package.json

### CODE REVIEW

**Comment by shaoshuai0102** [comment]
cc @popomore 要不要统一放到 egg-bin

**Comment by jtyjty99999** [comment]
+1  写起来确实清爽很多

**Comment by popomore** [comment]
统一不好放吧，要 require 的

**Comment by popomore** [comment]
+1

**Comment by atian25** [comment]
@popomore  `power-assert` 要 require, 但 `intelli-espower-loader` 可以内置到 egg-bin 去

**Comment by atian25** [comment]
@shaoshuai0102 不能引入 T_T
https://github.com/eggjs/egg-bin/pull/11#r79320925

**Comment by maxming2333** [comment]
赞

**Pull request merged**
