### PR TITLE
chore: update deps and test on node v7

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
@popomore 上次说要 review 下整个 views ?

**Comment by popomore** [comment]
view 的优先级不高，先 hold 的了

**Comment by popomore** [comment]
+1

**Comment by atian25** [comment]
0.6.0

**Pull request merged**
